### ISSUE TITLE
Unexpected token when installing apn.

### ISSUE THREAD

**Issue by j4nos** [node-apn/node-apn#475] opened 2016-11-16 13:13 UTC
Any idea what is wrong when installing apn on OpenShift?

DEBUG: Starting child process with 'node server.js'
/var/lib/openshift/555dd1415973ca1660000085/app-root/runtime/repo/node_modules/apn/index.js:28
	tls,
	   ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/lib/openshift/555dd1415973ca1660000085/app-root/runtime/repo/server.js:18:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
DEBUG: Program node server.js exited with code 8
DEBUG: Starting child process with 'node server.js'

**Comment by florianreinhart** [comment] 2016-11-16 13:16
Duplicate of #466

**Closed by florianreinhart** 2016-11-16 13:16 UTC
