### ISSUE TITLE
May be memory leak when "Not receiving Ping response after 150000 ms"

### ISSUE THREAD

**Issue by tian-yuan** [node-apn/node-apn#585] opened 2017-07-19 08:59 UTC
When "Not receiving Ping response after 150000 ms" occur, 
stream "error" event will be emitted, but stream do not release any more.
provider.shutdown() do not release stream resource also.

**Comment by funkenstrahlen** [comment] 2017-07-20 19:07
duplicate of #583

**Comment by hopye** [comment] 2017-09-14 04:48
Still no fix :/ :(

**Closed** 2017-09-29 07:57 UTC

**Comment by not2007** [comment] 2021-08-13 07:09
memory leak is fixed?
