### ISSUE TITLE
Not sending push notification in the production anymore

### ISSUE THREAD

**Issue by arpithparikh** [node-apn/node-apn#546] opened 2017-03-20 16:15 UTC
const PushNotifications = new require('node-pushnotifications');
const push = new PushNotifications(settings);const settings = {

    gcm: {
        id: "3273568XXXXX"

    },
    
    apn: {
        cert:path.join(__dirname ,'../', '/services/cert.pem'),
        key:path.join(__dirname ,'../', '/services/key.pem')
    }
};

    const data = {
        title: 'Hi', // REQUIRED
        body: "Hey Kai!" // REQUIRED,
    };
    var registrationIds = ['07fc9f468bc0fd4b8e7d06abbc4fa688f22ac8573a7e8e6f87f951029bddb09c'];
    push.send(registrationIds, data, function (err, result) {

        console.log(result);
        if (err) {
            console.log(err);
        } else {
            console.log(result);
        }
    });

**Comment by florianreinhart** [comment] 2017-03-20 16:32
Please provide more information

**Comment by arpithparikh** [comment] 2017-03-20 16:57
We used the Production SSL Certificate to generate both key.pem and cer.pem files — but it fails when trying to send a push notification to our production app. The odd part is: it was working fine when using the development key.pem and cer.pem files — even when the app was in production.

**Comment by DJHoltkamp** [comment] 2017-03-20 18:29
The key that works is based on what type of token you are sending to. Unless your app is already released by Apple, no production pushes are going to work (I believe TestFlight is sandbox too). Are you sure you are pushing to a device which downloaded the app from the AppStore?

**Comment by arpithparikh** [comment] 2017-03-20 19:11
Yes with production key.pem and cert.pem.

**Comment by arpithparikh** [comment] 2017-03-20 19:59
Is this NPM module only work for sendbox?Not for Production?

**Comment by florianreinhart** [comment] 2017-03-20 20:40
node-apn works in production as well as development/sandbox APNs environment.

Is your app released in the app store?

**Comment by arpithparikh** [comment] 2017-03-20 20:42
yes its released on the store.And eventually its stop working . Could you guide me what are the steps should I follow to debug why its not working ?

**Comment by florianreinhart** [comment] 2017-03-20 20:44
I would start by looking at any error returned in the send callback. Please provide as much information as you can.

**Comment by arpithparikh** [comment] 2017-03-20 21:02
{ regId: 'b8e6046582453dacb1814b304d888bab81ea4d1dcd6e52cbbb3f09cabb613e70', error: [Error: MissingTopic] } in callback return

**Comment by arpithparikh** [comment] 2017-03-20 21:16
Error: TopicDisallowed when I keep 'production:true' when I enable the topic:'something'!

**Comment by arpithparikh** [comment] 2017-03-20 21:28
is it enough details , or Do I need to send anything else @florianreinhart to figure out from your end?

**Comment by oliversalzburg** [comment] 2017-03-20 21:54
Possible duplicate of #514

**Comment by arpithparikh** [comment] 2017-03-20 21:56
got it! Thanks! Worked Perfectly!

**Closed** 2017-03-20 21:57 UTC
