### ISSUE TITLE
AssertionError: false == true in node-http2 lib/protocol/connection.js

### ISSUE THREAD

**Issue by rupey** [node-apn/node-apn#471] opened 2016-11-14 00:54 UTC
We're seeing this error fairly frequently in production after updating to node-apn 2.1.2:

```
AssertionError: false == true
    at Connection._send (/home/ec2-user/node/node_modules/http2/lib/protocol/connection.js:343:9)
    at Immediate.wrapped (/home/ec2-user/node/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Obviously, real bad news having an uncaught exception thrown inside a Promise like this.

It looks like node-apn is using a branch of node-http2 that recently changed the behaviour of that method (https://github.com/node-apn/node-http2/pull/1), might be a smoking gun what's causing this?

**Comment by rupey** [comment] 2016-11-15 02:39
Have done some more digging into this and it looks like that PR isn't to blame - the issue is something to do with the flow frame/window stuff in node-http2 and sending the alert to too many tokens at once is what provokes it.

Dispatch an alert to 1,000 tokens and the assertion fails reproducibly. Create 10 apn.Provider instances and dispatch to 100 tokens on each and so far everything goes smoothly.

**Comment by florianreinhart** [comment] 2016-11-15 18:21
@rupey looks like this is the same as #458

What node version are you running?

**Comment by rupey** [comment] 2016-11-16 00:55
Seeing this on both node 6.9.1 and 6.3.1.

**Comment by bbcelly** [comment] 2016-11-21 12:05
I had same problems on v6.9.1, but if I buffer requests and sending only one parallel request to APN, it works on v6.9.1 too. Not great, but it is working.

**Comment by hiddentao** [comment] 2016-11-22 12:34
We're having this problem too, stopping our server from even starting up.

**Comment by gpavel** [comment] 2016-11-30 11:35
I have same problem too when i send many push notifications at the same time.

Downgrade to node@4.2.3 and apn@2.1.1 helped me

**Comment by magicdawn** [comment] 2016-12-13 06:24
same problem

**Comment by recurrence** [comment] 2016-12-20 18:35
I never hit this issue when I exceed 20 notifications in a block, so my notification queues are throttling iOS notifications at 20 per block.  I'm not entirely time sensitive so it's fine and my android queues can still send blocks of 1000.

Obviously this isn't a solution but it is a temporary workaround that has worked for me until a solution is found.  I dropped an hour into this at first but didn't isolate the exact cause unfortunately.

**Comment by trx222** [comment] 2016-12-21 10:31
Same here

**Comment by IsaiahJTurner** [comment] 2017-01-01 21:24
I am using this as a workaround but it's somewhat slow (about a minute to send 100,000). Anyone have ideas to improve speed?
```
db.apns_full_view.find({}, {}, (err, apnses) => {
    if (err) {
        return console.error('Could not find apnses')
    }
    var apnsIds = []
    var batchStart = 0
    var batchSize = 100
    apnses.forEach(function(apns) {
        apnsIds.push(apns.apns_id)
    })
    process.setMaxListeners(0)

    function sendMore() {
        var currBatch = apnsIds.slice(batchStart, batchStart + batchSize)
        batchStart += batchSize
        console.log(batchStart, currBatch.length, apnsIds.length)
        apnProvider.send(new apn.Notification({
            alert: 'Hello world!',
        }), currBatch).then((responses) => {
            console.log('Sent push to ' + currBatch.length)
            if (currBatch.length > 0) {
                setTimeout(sendMore, 50)
            }
        }).catch((err) => console.error(err))
    }
    sendMore()
})
```

**Comment by mattisx** [comment] 2017-01-10 09:08
Having this too, as soon as sending to more than 7-800 devices.

**Comment by florianreinhart** [comment] 2017-01-10 09:12
@mattisx node version?

**Comment by mattisx** [comment] 2017-01-10 09:13
@florianreinhart 6.9.1

**Comment by zaumreit** [comment] 2017-01-10 09:15
Our team member also encountered the same problem today under node version 6.9.1.

**Comment by squallstar** [comment] 2017-01-11 21:14
Having the same issue on node 6.9.1 while sending notifications to around 1200 devices.

**Comment by danamajid** [comment] 2017-01-24 14:32
Same here. We're on node v6.3.1

@zaumreit are you saying you're not seeing this issue with a version greater than 6.9.1?

**Comment by sbeff** [comment] 2017-02-04 17:00
I have the same problem when I try to send a notification to multiple devices and I set a bigger payload. Now I have to send around 200 notifications per provider connection, and it's very frustrating.
Node version: v6.9.4

**Comment by behrad** [comment] 2017-02-05 11:02
+1

**Comment by taina0407** [comment] 2017-02-05 11:04
I think we should +1 in node-http2 repository https://github.com/molnarg/node-http2/issues/228

**Comment by sbeff** [comment] 2017-02-06 14:01
What type of authentication are you guys using? It could be related to this error. I'm using Json Web Tokens.

**Comment by davidbnk** [comment] 2017-02-08 00:12
I'm having this problem also. Reducing the batch size to 100 tokens solved for me

**Comment by chrisrecalis** [comment] 2017-02-08 12:57
We ended up downgrading from node v6.4.0 to v5.11.1 and haven't seen this error since. Originally we would get the assertion error sending 20 or more notifications on the same client on v6.4.0

**Comment by jeacott1** [comment] 2017-02-14 21:45
+1

**Comment by xuduo** [comment] 2017-02-28 07:54
+1 on node 6.9.4

**Comment by Xzya** [comment] 2017-02-28 21:38
We had the same problem and solved it by sending batches of 100 tokens instead of 1000. However, the biggest problem we are facing is with memory consumption. The memory doesn't seem to be deallocated properly. We are sending around 400k iOS notifications and we need 3 servers with 2gb of ram to handle the memory pressure. As a comparison, 1.5m android tokens use around 200mb on each server. This can be reproduced by continously generating random tokens and sending a notification to them, the memory will keep growing and not get deallocated.

**Comment by IsaiahJTurner** [comment] 2017-03-06 15:26
It looks like this repo is about dead. Is there an alternative?

**Comment by mattisx** [comment] 2017-03-06 15:27
I really need to get this to work, our whole system is starting to depend on it.

**Comment by florianreinhart** [comment] 2017-03-06 15:44
@IsaiahJTurner This is an issue in node-http2 and not in node-apn https://github.com/molnarg/node-http2/issues/228

**Comment by IsaiahJTurner** [comment] 2017-03-06 15:52
@florianreinhart Is it possible to migrate away from node-http2? Perhaps to https://github.com/nodejs/http2

**Comment by IsaiahJTurner** [comment] 2017-03-06 16:01
# Bug Bounty
https://www.bountysource.com/issues/39200654-assertionerror-false-true-in-node-http2-lib-protocol-connection-js

I posted $50 but if anyone else depends on this, feel free to raise it. Hopefully we can motivate someone to fix this issue as soon as possible.

**Comment by florianreinhart** [comment] 2017-03-06 16:03
@IsaiahJTurner We will definitely migrate to node's native HTTP/2 implementation. I am closely following that repo and there is currently no HTTP/2 client implementation. They just started working on it.

**Comment by florianreinhart** [comment] 2017-03-06 16:07
@IsaiahJTurner We actually already using a fork of node-http2 to fix some other issues in the library.

**Comment by oliversalzburg** [comment] 2017-03-07 13:28
@mattisx If you **really** need to get this to work, open a pull request :)

**Comment by xuduo** [comment] 2017-03-08 02:40
update: 
node 6.2.2 works fine for me.
It's a node-http2 problem.
Basically after node 6.2.2, 4 tests of node-http2 starts to fail.

**Comment by jrabek** [comment] 2017-03-09 19:07
https://github.com/molnarg/node-http2/pull/236
https://github.com/molnarg/node-http2/pull/235

**Comment by florianreinhart** [comment] 2017-03-09 19:28
Thanks @jrabek.

However, I don't believe the PRs will be merged. The node-http2 repo seems to be dead. If someone has the time to create a PR against [our node-http2 fork](https://github.com/node-apn/node-http2), that would be great.

**Comment by jrabek** [comment] 2017-03-09 22:23
We ended up doing the fix on our own fork of node-apn (https://github.com/airtimemedia/node-apn/commits/flow-fix) and testing the fix out fairly thoroughly 
 with load tests and using valid and invalid tokens (which seems to trigger the http2 flow control to kick in more).

**Comment by danamajid** [comment] 2017-03-10 19:22
The actual fixes (mentioned above) were applied to our own fork of `node-http2` (which we forked off of node-apn's depedency): https://github.com/airtimemedia/node-http2/commits/flow-fix

**Comment by cmdkoh** [comment] 2017-03-12 06:52
@florianreinhart can we link this issue to #521 - it seems like the same issue?

**Comment by thughes** [comment] 2017-03-14 21:56
Sorry, somehow I missed the updates to this.

@florianreinhart I went ahead and opened PRs against your forked `node-http2` since the ones in molnarg/node-http2 have had no action:
https://github.com/node-apn/node-http2/pull/2
https://github.com/node-apn/node-http2/pull/3

**Closed** 2017-03-15 08:53 UTC

**Comment by florianreinhart** [comment] 2017-03-15 08:55
Thanks a lot, @thughes!

**Comment by taina0407** [comment] 2017-03-21 09:33
@florianreinhart When will you release path for node-http2 and node-apn ?
