### ISSUE TITLE
BadDeviceToken issue

### ISSUE THREAD

**Issue by DeerBeer** [node-apn/node-apn#526] opened 2017-02-16 19:57 UTC
Hello,

I just switched from version 1.7.3 to 2.1.3. Changed the code to go through provider not connection like eralier and for all request I receive BadDeviceToken. I switch back to 1.7.3 and old code and it's working with same token and same certificates. Is that some known issue. If needed I can send more details.

**Comment by DeerBeer** [comment] 2017-02-17 15:49
Update: from version 2+ working only with 2.1.2

**Comment by ArdentZeal** [comment] 2017-02-17 16:48
I am not getting mine to work either.

1. base64Token : LrXX55040oVLHzQqHUmyWlwhT4ZdU97XbF8YGuOp3bo=
This one I send to the server and save it.

2. I am using Buffer.from(result.deviceToken, 'base64').toString('hex') to generate following hextoken
2eb5d7e79d38d2854b1f342a1d49b25a5c214f865d53ded76c5f181ae3a9ddba

I am sending that via node-apn 

Notification failed! 2eb5d7e79d38d2854b1f342a1d49b25a5c214f865d53ded76c5f181ae3a9ddba 400 { reason: 'BadDeviceToken' }

I tried setting production: true, I tried version 2.1.3 and 2.1.2.

nothing seems to work. 

Does anyone have any tipps I can try?

Kind Regards

**Comment by extempl** [comment] 2017-02-27 12:38
@DeerBeer Probably you should set `production: true` if using DIstribution prov profile. That was the issue in my case, not sure how it may be related to apn version, though.

**Comment by DeerBeer** [comment] 2017-02-27 13:21
That is not the case, the environments - token - certificates matches. The same token, same certificates same environments didn't worked till I switched to 2.1.2.

**Comment by florianreinhart** [comment] 2017-03-06 15:56
@DeerBeer this is strange. I am not able to reproduce that issue and I don't see anything that has changed from 2.1.2 to 2.1.3.

Could you try to find out what commit between 2.1.2 and 2.1.3 introduced the issue?

**Comment by florianreinhart** [comment] 2017-06-29 12:09
@DeerBeer Do have any additional insights to this issue?

**Comment by DeerBeer** [comment] 2017-06-29 12:41
@florianreinhart no, I left it on 2.1.2 and resolved my issue that way and immediately been trowed on another issue.

**Comment by florianreinhart** [comment] 2017-06-29 12:44
OK, since we cannot reproduce this, I'll close the issue for now. It would be great if you could try to reproduce the issue with the latest version.

**Closed by florianreinhart** 2017-06-29 12:44 UTC
