### ISSUE TITLE
The message was sent successfully, but the phone could not receive it

### ISSUE THREAD

**Issue by lijinke666** [node-apn/node-apn#599] opened 2017-10-19 08:13 UTC
Hi ~ I found this module today, It's very nice , I can send it normally at noon,  but now my test phone There's no information

This is `result`

```js
result: '{"sent":[{"device":'xxx"}],"failed":[]}' }
```

My code is
```js
    const providerOptions = {
            cert:certPath,
            key:keyPath,
            geteway:GATE_WAY,
            passphrase: PROD_PASSWORD, //pem证书密码 
            production:mode == "development" ? false : true
        }
        const service = new apn.Provider(providerOptions)
        const note = new apn.Notification()
        note.expiry = Math.floor(Date.now() / 1000) + 3600; // 有效期  一小时.
        note.badge = Number(badge) || 0
        note.sound = "default"
        note.alert = `${messageTitle} : ${messageContent}`
        note.payload = {'messageFrom':"legendpoker"}
        note.topic = BUNDLE_ID;

 service.send(note,deviceTokens).then((result)=>{
     ...
 }
```
I don't know why , can you help me ?

**Comment by diemto** [comment] 2017-10-24 19:50
I'm also facing the same problem!

**Comment by yury-kalinkin** [comment] 2017-10-26 10:47
Same issue.

**Comment by sebastiandanilonr** [comment] 2017-10-30 19:40
I'm facing the same problem. Also, de iOS app doesn't show the dialog asking permission for the push notifications, is this the same case for you?
Anyone has found a solution?
Thanks!

**Comment by lijinke666** [comment] 2017-10-31 03:04
@diemto @yury-kalinkin @sebastiandanilonr  Hi~ , I found out if I wasn't in the app ( In the home page ) ,  is can Accept to of the iOS push message,
Every time I run the test code , my app is open, the message is not accept, Then i toggle my phone in the home page,  run my code again, Successful message accept
of course , you shoud promise your `key`,`pem` and `topic`  no problem

**Comment by sebastiandanilonr** [comment] 2017-11-01 16:55
@lijinke666 Yes, this is the normal behavior if you don't handle the notifications when your app is on focus. The problem is that the notifications don't reach the device in any case.

**Comment by wiggisser** [comment] 2017-11-28 09:19
@sebastiandanilonr If your iOS app does not ask for permisson at least once, it is not registered for APN. If you have a valid device token you must have at least once been asked for permission. If you really never have been ask for permisson, you can't have a device token, and therefore can't send to this particular device. 

Also make sure you are using the correct environment. Eventhough the certificates may now be usable for sandbox and production, you must specify whether your build is a develpment or production build.

**Comment by shubhankit92** [comment] 2018-01-31 10:50
I am also facing the same problem...everything worked fine except the notification are not getting received.
please reply if any one finds the answer..
https://stackoverflow.com/questions/48539732/unable-to-receive-web-push-notifications-on-safari-browser-even-having-sent-the

**Comment by florianreinhart** [comment] 2018-04-24 12:37
@wiggisser Your explanation is not correct.

Apple changed this a while ago. You now get a device token without asking for permission. This allows you to send silent notifications that are received by your app in the background.

However, if you want to show a notification to the user, you need to request permission.

I am closing this issue. This is a configuration issue in your iOS apps.

**Closed by florianreinhart** 2018-04-24 12:37 UTC
